### ISSUE TITLE
Deep interest to use your code as an open-source application

### ISSUE THREAD

**Issue by momo1986** [melonwan/sphereHand#1]
Dear researchers,

I have some projects to use the tools of 3D hand pose reconstruction.

I am wondering, could I use your code as an open-source application with citation?

I am very interested in your self-learning algorithm.

Thanks & Regards!

**Comment by melonwan** [comment]
apologies for the delay. The paper was published right before my graduation, and I failed to publish the code before leaving the University. After that, I didn't manage to buy a PC and clean the code to publish. Sorry for the procrastination. I'll buy the PC and publish the code this summer.

Yes, there are visualization and optimization tools in the source code for 3D hand pose reconstruction. Sorry for the delay, the code will be coming soon.
